FROM alpine AS builder

RUN apk -U add automake autoconf build-base make pkgconf
COPY . /src
WORKDIR /src
RUN autoreconf -i
RUN ./configure --prefix=/install
RUN make install

FROM alpine
COPY --from=builder /install /install
